# MetaSnakePipe
# Original MetaGenePipe workflow by Bobbie Shaban
# Snakemake port by Vini Salazar (with modifications)
from pathlib import Path


configfile: "config/config.yaml"


##### load rules #####
include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/assembly.smk"
include: "rules/mapping.smk"
include: "rules/binning.smk"
include: "rules/annotation.smk"
include: "rules/postprocessing.smk"


rule all:
    """
    Requires all final outputs.
    """
    input:
        final_output=get_final_output(),
        postprocessing=get_postprocessing_output()
        if is_activated("postprocessing")
        else None,
