# MetaSnakePipe
# Original MetaGenePipe workflow by Bobbie Shaban
# Snakemake port by Vini Salazar (with modifications)
configfile: "config/config.yaml"


##### load rules #####
include: "rules/common.smk"
include: "rules/preprocess.smk"
include: "rules/assembly.smk"
include: "rules/mapping.smk"
include: "rules/annotation.smk"


rule all:
    input:
        * get_final_output(),
