# Based on the Snakemake RNASeq workflow:
#   https://github.com/snakemake-workflows/rna-seq-star-deseq2/

# Make sure that the module separators have the same amount
# of '#' characters as they are parsed by scripts from the documentation.

###############################################################
# TOP LEVEL
# These settings are valid for all steps in the workflow.
###############################################################

# Path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).

samples: samples.csv

# CPU settings
# Total cores are passed from the command line
cores_per_big_task: 1         # Total of workflow cores to use per big task
cores_per_medium_task: 0.5    # Total of workflow cores to use per medium task
cores_per_small_task: 0.25    # Total of workflow cores to use per small task

# Memory settings
max_mb: 65536         # Max MB memory to be used. This sould be over the number of 'cores * mb_per_core'. Must correspond to the maximum resources requested from the machine (e.g. in a cluster).
mb_per_core: 2048     # How many MBs of RAM to use per processor. For more information about this, read the "Advanced" page of the docs.

###############################################################
# QC
###############################################################

cutadapt:
  activate: True
  phred: 33
  minimum_length: 50
  quality_cutoff: 30
  clip_r5: 10
  clip_r3: 5

merge_reads:
  activate: True

fastqc:
  activate: True

multiqc:
  activate: True

###############################################################
# ASSEMBLY
###############################################################
coassembly: False  # Whether to perform coassembly (also known as pooled assembly). If this is true, all samples are merged together and assembled into a single file of contigs.

# Parameters should be named after the corresponding rule
concatenate_contigs:
  sequence_length_cutoff: 1

megahit:
  preset: "meta-large"
  cleanup: True

metaquast:
  activate: False
  coassembly_reference: ""  # Reference FASTA file for Metaquast to use as reference. Only required if `coassembly` is True.

###############################################################
# ANNOTATION
###############################################################

prodigal:
  activate: True
  mode: "meta"
  quiet: True
  genes: False
  scores: False

prokka:
  activate: False
  args: "--metagenome --quiet --force"
  kingdom: "Bacteria"

diamond:
  db: "data/COG2020/cog-20.dmnd"      # Will try to create from db_source if it doesn't exist.
  db_source: "data/COG2020/cog-20.fa.gz"
  output_type: 6
  output_format: "qseqid sseqid stitle evalue bitscore staxids sscinames"

cog_functional_parser:
  activate: True
  db: "data/COG2020"

lineage_parser:
  activate: True
  taxonmap: "data/COG2020/cog-20.taxonmap.tsv"
  rankedlineage: "data/taxonomy/rankedlineage.dmp"
  names: "data/taxonomy/names.dmp"  # Path of names file of NCBI Taxonomy 
  nodes: "data/taxonomy/nodes.dmp"  # Path of nodes file of NCBI Taxonomy
  download_url: "https://ftp.ncbi.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz"  # URL to download NCBI Taxonomy database

plot_cog_functional:
  activate: True
  filter_categories: True
  categories_cutoff: 0.01

plot_taxonomies:
  activate: True
  tax_cutoff: 0.000001  # 1e-6

###############################################################
# BINNING
###############################################################

vamb:
  activate: True
  minfasta: 10000

metabat2:
  activate: True
  seed: 0
  preffix: "bin"  # Preffix of each bin, e.g. bin.1.fa, bin.2.fa, etc.

concoct:
  activate: True

das_tool:
  activate: True
  score_threshold: 0.5

###############################################################
# POSTPROCESSING
###############################################################

postprocessing:
  activate: True
  runtime_unit: "m"
  runtime_cutoff: 5
  memory_unit: "max_vms"
  memory_cutoff: 1
  memory_gb: True
