# Based on the Snakemake RNASeq workflow:
#   https://github.com/snakemake-workflows/rna-seq-star-deseq2/

###############################################################
# TOP LEVEL
# These settings are valid for all steps in the workflow.
###############################################################

# Path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
samples: samples.csv

# Path to the Metaphor data directory, where databases (COG, EggNOG, NCBI Taxonomy)
# will be installed. Leave 'DEFAULT' if using the Metaphor installation directory
data_dir: DEFAULT

# CPU settings
# Total cores are passed from the command line
cores_per_big_task: 1         # Total of workflow cores to use per big task
cores_per_medium_task: 0.5    # Total of workflow cores to use per medium task
cores_per_small_task: 0.25    # Total of workflow cores to use per small task

# Memory settings
max_mb: 8192          # Max MB memory to be used.
scheduler: False  # Set this to False when running on a cluster. It makes better usage of memory settings on each node.

# Plotting
transparent_background: True  # Whether to draw figures with a transparent background
dpi: 600  # Dots per inch (quality of figures). 600 is publication-level quality.
output_format: "png"  # Output format of plots. Values are the ones supported by plt.savefig().

###############################################################
# QC
###############################################################

fastp:
  activate: True
  length_required: 50
  cut_mean_quality: 30
  extra: "--detect_adapter_for_pe"

merge_reads:
  activate: True

host_removal:
  activate: False
  reference: ""

fastqc:
  activate: False

multiqc:
  activate: False

###############################################################
# Assembly
###############################################################

coassembly: False

megahit:
  preset: "meta-large"
  min_contig_len: 200
  remove_intermediate_contigs: True

rename_contigs:
  activate: True  # Whether to rename contigs so contigs and mapping files (.bam) can be imported into Anvi'o. We suggest you keep this on.
  awk_command: awk '/^>/{{gsub(" |\\\\.|=", "_", $0); print $0; next}}{{print}}' {input} > {output}  # This is to prevent errors with the Snakemake --lint command. Don't change it unless you know what you're doing.

metaquast:
  activate: False
  coassembly_reference: ""  # only required if 'coassembly' is True

###############################################################
# Annotation
###############################################################

prodigal:
  activate: True
  mode: "meta"
  quiet: True
  genes: False
  scores: False

prokka:
  activate: True
  args: "--quiet --force"

diamond:
  db: "COG2020/cog-20.dmnd"  # for testing purposes only
  output_type: 6
  output_format: "qseqid sseqid stitle evalue bitscore staxids sscinames"

cog_functional_parser:
  activate: True
  db: "COG2020"

lineage_parser:
  activate: False
  taxonmap: "COG2020/cog-20.taxonmap.tsv"
  rankedlineage: "taxonomy/rankedlineage.dmp"
  names: "taxonomy/names.dmp"
  nodes: "taxonomy/nodes.dmp"
  download_url: "https://ftp.ncbi.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz"

plot_cog_functional:
  activate: True
  filter_categories: True
  categories_cutoff: 0.01


plot_taxonomies:
  activate: True
  tax_cutoff: 20  # Only show the N most abundant taxa for any rank. Low abundance taxa will be grouped as 'undetermined/other'.
  colormap: "tab20c"  # Which matplotlib colormap to use

###############################################################
# Binning
###############################################################

cobinning: True # Whether to perform cobinning. When this is true, only one binning group will be used. If False, samples will be binned according to their 'group' column.

vamb:
  activate: False
  minfasta: 1000
  batchsize: 128

metabat2:
  activate: True
  seed: 0
  preffix: "bin"  # preffix of each bin, e.g. bin.1.fa, bin.2.fa, etc

concoct:
  activate: False  # CONCOCT installation can be problematic in some OSs so this is disabled for testing

das_tool:
  activate: False
  score_threshold: 0.05
  bins_report: False

###############################################################
# Postprocessing
###############################################################

postprocessing:
  activate: True
  runtime_unit: "m"
  runtime_cutoff: 0
  memory_unit: "max_vms"
  memory_cutoff: 0
  memory_gb: True
