# Based on the Snakemake RNASeq workflow:
#   https://github.com/snakemake-workflows/rna-seq-star-deseq2/

###############################################################
# TOP LEVEL
# These settings are valid for all steps in the workflow.
###############################################################

# Path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
samples: samples.csv

# CPU settings
# Total cores are passed from the command line
cores_per_big_task: 1         # Total of workflow cores to use per big task
cores_per_medium_task: 0.5    # Total of workflow cores to use per medium task
cores_per_small_task: 0.25    # Total of workflow cores to use per small task

# Memory settings
max_mb: 8196          # Max MB memory to be used.


###############################################################
# QC
###############################################################

cutadapt:
  activate: True
  phred: 33
  minimum_length: 50
  quality_cutoff: 30
  clip_r5: 10
  clip_r3: 5

merge_reads:
  activate: True

host_removal:
  activate: False
  reference: ""

fastqc:
  activate: False

multiqc:
  activate: False

###############################################################
# Assembly
###############################################################

coassembly: False

concatenate_contigs:
  sequence_length_cutoff: 500

megahit:
  preset: "meta-large"
  cleanup: True

metaquast:
  activate: False
  coassembly_reference: ""  # only required if 'coassembly' is True

###############################################################
# Annotation
###############################################################

prodigal:
  activate: True
  mode: "meta"
  quiet: True
  genes: False
  scores: False

prokka:
  activate: False
  args: "--metagenome --quiet --force"
  kingdom: "Bacteria"

diamond:
  db: "data/COG2020/cog-20.dmnd"  # for testing purposes only
  output_type: 6
  output_format: "qseqid sseqid stitle evalue bitscore staxids sscinames"

cog_functional_parser:
  activate: True
  db: "data/COG2020"

lineage_parser:
  activate: False
  taxonmap: "data/COG2020/cog-20.taxonmap.tsv"
  rankedlineage: "data/taxonomy/rankedlineage.dmp"
  names: "data/taxonomy/names.dmp"
  nodes: "data/taxonomy/nodes.dmp"
  download_url: "https://ftp.ncbi.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz"

plot_cog_functional:
  activate: True
  filter_categories: True
  categories_cutoff: 0.01


plot_taxonomies:
  activate: True
  tax_cutoff: 0.01

###############################################################
# Binning
###############################################################

cobinning: True # Whether to perform cobinning. When this is true, only one binning group will be used. If False, samples will be binned according to their 'group' column.

vamb:
  activate: True
  minfasta: 1000
  batchsize: 128

metabat2:
  activate: True
  seed: 0
  preffix: "bin"  # preffix of each bin, e.g. bin.1.fa, bin.2.fa, etc

concoct:
  activate: False

das_tool:
  activate: True
  score_threshold: 0.0

###############################################################
# Postprocessing
###############################################################

postprocessing:
  activate: True
  runtime_unit: "m"
  runtime_cutoff: 0
  memory_unit: "max_vms"
  memory_cutoff: 0
  memory_gb: True
