$schema: "http://json-schema.org/draft-06/schema#"

description: Snakemake configuration file

type: object

properties:
  samples:
    type: string
  
  units:
    type: string

  resources:
    type: object
    properties:
      mb_per_thread:
        type: integer
    required:
      - mb_per_thread

###############################################################
# QC
###############################################################

  trimming:
    type: object
    properties:
      activate:
        type: boolean
      phred:
        type: integer
      minimum_length:
        type: integer
      quality_cutoff:
        type: integer
      clip_r5:
        type: integer
      clip_r3:
        type: integer
    required:
      - activate
      - phred
      - minimum_length
      - quality_cutoff
      - clip_r5
      - clip_r3

  merge_reads:
    type: object
    properties:
      activate:
        type: boolean
    required:
      - activate

###############################################################
# Assembly
###############################################################

  coassembly:
    type: boolean

  concatenate_contigs:
    type: object
    properties:
      sequence_length_cutoff: 
        type: integer
    required:
      - sequence_length_cutoff

  megahit:
    type: object
    properties:
      preset:
        type: string
      cleanup:
        type: boolean
    required:
      - preset
      - cleanup

  metaquast:
    type: object
    properties:
      activate:
        type: boolean
      coassembly_reference:
        type: string
    required:
      - activate

###############################################################
# Annotation
###############################################################

  prodigal:
    type: object
    properties:
      activate:
        type: boolean
      mode:
        type: string
      quiet:
        type: boolean
      genes:
        type: boolean
      scores:
        type: boolean
    required:
      - activate
      - mode
      - quiet
      - genes
      - scores

  prokka:
    type: object
    properties:
      activate:
        type: boolean
      args:
        type: string
      kingdom:
        type: string
    required:
      - activate
      - args
      - kingdom

  diamond:
    type: object
    properties:
      db:
        type: string
      db_source:
        type: string
      output_type:
        type: integer
      output_format:
        type: string
    required:
      - db
      - db_source

  cog_functional_parser:
    type: object
    properties:
      db:
        type: string
      activate:
        type: boolean
    required:
      - db
      - activate
      
  lineage_parser:
    type: object
    properties:
      activate:
        type: boolean
      taxonmap:
        type: string
      rankedlineage:
        type: string
      names:
        type: string
      nodes:
        type: string
      download_url:
        type: string
    required:
      - activate
      - taxonmap
      - rankedlineage
      - names
      - nodes
      - download_url

  plot_cog_functional:
    type: object
    properties:
      activate:
        type: boolean
      filter_categories:
        type: boolean
      categories_cutoff:
        type: number
    required:
      - activate
      - filter_categories
      - categories_cutoff

  plot_taxonomies:
    type: object
    properties:
      tax_cutoff:
        type: number
    required:
      - tax_cutoff

###############################################################
# Binning
###############################################################

  vamb:
    type: object
    properties:
      activate:
        type: boolean
      minfasta:
        type: integer
    required:
      - activate
      - minfasta

  metabat2:
    type: object
    properties:
      activate:
        type: boolean
      seed:
        type: integer
      preffix:
        type: string
    required:
      - activate
      - seed
      - preffix

  concoct:
    type: object
    properties:
      activate:
        type: boolean
    required:
      - activate

  das_tool:
    type: object
    properties:
      activate:
        type: boolean
      score_threshold:
        type: number
    required:
      - activate
      - score_threshold

###############################################################
# Postprocessing
###############################################################

  postprocessing:
    type: object
    properties:
      activate:
        type: boolean
      runtime_unit:
        type: string
      runtime_cutoff:
        type: integer
      memory_unit:
        type: string
      memory_cutoff:
        type: integer
      memory_gb:
        type: boolean
    required:
      - activate
      - runtime_unit
      - runtime_cutoff
      - memory_unit
      - memory_cutoff
      - memory_gb

required:
  - samples
  - coassembly
  - resources
  - trimming
  - merge_reads
  - concatenate_contigs
  - megahit
  - metaquast
  - prodigal
  - prokka
  - diamond
  - cog_functional_parser 
  - lineage_parser
  - plot_cog_functional
  - plot_taxonomies
  - vamb
  - metabat2
  - concoct
  - das_tool
  - postprocessing
