$schema: "http://json-schema.org/draft-06/schema#"

description: Snakemake configuration file

type: object

properties:
  samples:
    type: string
  
  units:
    type: string

  cores_per_big_task:
    type: number
  cores_per_medium_task:
    type: number
  cores_per_small_task:
    type: number

  max_mb:
    type: integer
  local_execution:
    type: boolean

###############################################################
# QC
###############################################################

  cutadapt:
    type: object
    properties:
      activate:
        type: boolean
      phred:
        type: integer
      minimum_length:
        type: integer
      quality_cutoff:
        type: integer
      clip_r5:
        type: integer
      clip_r3:
        type: integer
    required:
      - activate
      - phred
      - minimum_length
      - quality_cutoff
      - clip_r5
      - clip_r3

  merge_reads:
    type: object
    properties:
      activate:
        type: boolean
    required:
      - activate

  host_removal:
    type: object
    properties:
      activate:
        type: boolean
      reference:
        type: string
    required:
      - activate
      - reference

  fastqc:
    type: object
    properties:
      activate:
        type: boolean
    required:
      - activate

  multiqc:
    type: object
    properties:
      activate:
        type: boolean
    required:
      - activate

###############################################################
# Assembly
###############################################################

  coassembly:
    type: boolean

  megahit:
    type: object
    properties:
      preset:
        type: string
      cleanup:
        type: boolean
      min_contig_len:
        type: integer
    required:
      - preset
      - cleanup
      - min_contig_len

  metaquast:
    type: object
    properties:
      activate:
        type: boolean
      coassembly_reference:
        type: string
    required:
      - activate

###############################################################
# Annotation
###############################################################

  prodigal:
    type: object
    properties:
      activate:
        type: boolean
      mode:
        type: string
      quiet:
        type: boolean
      genes:
        type: boolean
      scores:
        type: boolean
    required:
      - activate
      - mode
      - quiet
      - genes
      - scores

  prokka:
    type: object
    properties:
      activate:
        type: boolean
      args:
        type: string
    required:
      - activate
      - args

  diamond:
    type: object
    properties:
      db:
        type: string
      db_source:
        type: string
      output_type:
        type: integer
      output_format:
        type: string
    required:
      - db
      - db_source

  cog_functional_parser:
    type: object
    properties:
      db:
        type: string
      activate:
        type: boolean
    required:
      - db
      - activate
      
  lineage_parser:
    type: object
    properties:
      activate:
        type: boolean
      taxonmap:
        type: string
      rankedlineage:
        type: string
      names:
        type: string
      nodes:
        type: string
      download_url:
        type: string
    required:
      - activate
      - taxonmap
      - rankedlineage
      - names
      - nodes
      - download_url

  plot_cog_functional:
    type: object
    properties:
      activate:
        type: boolean
      filter_categories:
        type: boolean
      categories_cutoff:
        type: number
    required:
      - activate
      - filter_categories
      - categories_cutoff

  plot_taxonomies:
    type: object
    properties:
      activate:
        type: boolean
      tax_cutoff:
        type: integer
      colormap:
        type: string
    required:
      - activate
      - tax_cutoff
      - colormap

###############################################################
# Binning
###############################################################

  cobinning:
    type: boolean

  vamb:
    type: object
    properties:
      activate:
        type: boolean
      minfasta:
        type: integer
      batchsize:
        type: integer
    required:
      - activate
      - minfasta
      - batchsize

  metabat2:
    type: object
    properties:
      activate:
        type: boolean
      seed:
        type: integer
      preffix:
        type: string
    required:
      - activate
      - seed
      - preffix

  concoct:
    type: object
    properties:
      activate:
        type: boolean
    required:
      - activate

  das_tool:
    type: object
    properties:
      activate:
        type: boolean
      score_threshold:
        type: number
      bins_plot:
        type: boolean
    required:
      - activate
      - score_threshold
      - bins_report

###############################################################
# Postprocessing
###############################################################

  postprocessing:
    type: object
    properties:
      activate:
        type: boolean
      runtime_unit:
        type: string
      runtime_cutoff:
        type: integer
      memory_unit:
        type: string
      memory_cutoff:
        type: integer
      memory_gb:
        type: boolean
    required:
      - activate
      - runtime_unit
      - runtime_cutoff
      - memory_unit
      - memory_cutoff
      - memory_gb

required:
  - samples
  - coassembly
  - max_mb
  - local_execution
  - cutadapt
  - merge_reads
  - host_removal
  - fastqc
  - multiqc
  - megahit
  - metaquast
  - prodigal
  - prokka
  - diamond
  - cog_functional_parser 
  - lineage_parser
  - plot_cog_functional
  - plot_taxonomies
  - cobinning
  - vamb
  - metabat2
  - concoct
  - das_tool
  - postprocessing
