channels:
  - bioconda
  - conda-forge
dependencies:
  - mamba               # recommended for use with conda
  - pandas
  - requests
  - snakemake-minimal
  - snakefmt            # required for development
  - tqdm                # required for cli
  - pyyaml              # required for cli
