name: metaphor-dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - ipython             # dev
  - jinja2              # required for reports
  - myst-parser         # dev
  - networkx            # required for reports
  - pandas
  - pyyaml              # required for cli
  - requests
  - snakemake
  - snakemake-wrapper-utils=0.3.1
  - snakefmt            # dev
  - sphinx              # dev
  - tqdm                # required for cli