name: metaphor
channels:
  - conda-forge
  - bioconda
dependencies:
  - jinja2              # required for reports
  - networkx            # required for reports
  - pandas
  - pyyaml              # required for cli
  - requests
  - snakemake>=7
  - snakemake-wrapper-utils
  - tqdm                # required for cli