channels:
  - conda-forge
  - bioconda
dependencies:
  - jinja2              # required for reports
  - networkx            # required for reports
  - pandas
  - pyyaml              # required for cli
  - requests
  - snakemake
  - snakemake-wrapper-utils
  - snakefmt            # required for development
  - tqdm                # required for cli
