"""
Metaphor - Metagenomic Pipeline for Short Reads

The University of Melbourne

A joint effort between the School of Mathematics & Statistics, School of BioSciences
and the Melbourne Data Analytics Platform (MDAP).
"""

__author__ = "Vini Salazar"

from pathlib import Path


configfile: "metaphor/config/default-config.yaml"


report: "metaphor/report/metaphor.rst"


##### load rules #####
include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/assembly.smk"
include: "rules/mapping.smk"
include: "rules/binning.smk"
include: "rules/annotation.smk"
include: "rules/postprocessing.smk"


rule all:
    """
    Requires all final outputs.
    """
    input:
        final_output=get_final_output(),
        postprocessing=get_postprocessing_output()
        if is_activated("postprocessing")
        else None,
