# Based on the Snakemake RNASeq workflow:
#   https://github.com/snakemake-workflows/rna-seq-star-deseq2/

# Path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/patdec_samples.csv

# Path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: config/patdec_units.csv


trimming:
  activate: True
  phred: 33
  minimum_length: 50
  quality_cutoff: 30
  clip_r5: 10
  clip_r3: 5

merge_reads:
  activate: True

# Parameters should be named after the corresponding rule
concatenate_contigs:
  sequence_length_cutoff: 1

megahit:
  preset: "meta-large"

prodigal:
  mode: "meta"

hmmsearch:
  db: ".test/data/hmmer-test.hmm"

diamond:
  db: ".test/data/swissprot.dmnd"  # for testing purposes only
  output_type: 6
  output_format: "qseqid sseqid stitle pident length mismatch gapopen qstart qend sstart send evalue bitscore"

hmmer_parser:
  db: ".test/data/brite.txt"
  consistent_pathways: True

diamond_parser:
  db: ".test/data/taxonomic_lineages.pickle"
  activate: False

vamb:
  activate: False

metabat2:
  activate: True
  seed: 0
  preffix: "bin"  # preffix of each bin, e.g. bin.1.fa, bin.2.fa, etc

concoct:
  activate: True
