# Based on the Snakemake RNASeq workflow:
#   https://github.com/snakemake-workflows/rna-seq-star-deseq2/

# Path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/samples.csv

# Path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: config/units.csv


trimming:
  activate: True
  phred: 33
  minimum_length: 50
  quality_cutoff: 30
  clip_r5: 10
  clip_r3: 5

merge_reads:
  activate: True

# Parameters should be named after the corresponding rule
concatenate_contigs:
  sequence_length_cutoff: 1

megahit:
  preset: "meta-large"

metaquast:
  activate: False
  reference: ""

prodigal:
  mode: "meta"

prokka:
  activate: True
  args: "--metagenome --quiet --force"
  kingdom: "Bacteria"

diamond:
  db: ".test/cog-20-patmg.dmnd"  # for testing purposes only
  output_type: 6
  output_format: "qseqid sseqid stitle pident length mismatch gapopen qstart qend sstart send evalue bitscore"

cog_parser:
  db: ".test/COG2020"
  activate: False

vamb:
  activate: False

metabat2:
  activate: True
  seed: 0
  preffix: "bin"  # preffix of each bin, e.g. bin.1.fa, bin.2.fa, etc

concoct:
  activate: False

das_tool:
  activate: False

postprocessing:
  activate: True
  runtime_unit: "m"
  runtime_cutoff: 0
  memory_unit: "max_vms"
  memory_cutoff: 0
  memory_gb: True