samples: "config/samples.csv"

# Parameters should be named after the corresponding rule
concatenate_contigs:
  sequence_length_cutoff: 1  # the script's default is 2000

prodigal:
  mode: "single"

diamond:
  db: ".test/data/swissprot-1k.dmnd"  # for testing purposes only
