$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  
  units:
    type: string

  trimming:
    type: object
    properties:
      activate:
        type: boolean
      phred:
        type: integer
      minimum_length:
        type: integer
      quality_cutoff:
        type: integer
      clip_r5:
        type: integer
      clip_r3:
        type: integer
    required:
      - activate
      - phred
      - minimum_length
      - quality_cutoff
      - clip_r5
      - clip_r3

  merge_reads:
    type: object
    properties:
      activate:
        type: boolean
    required:
      - activate

  concatenate_contigs:
    type: object
    properties:
      sequence_length_cutoff: 
        type: integer
    required:
      - sequence_length_cutoff

  megahit:
    type: object
    properties:
      preset:
        type: string
    required:
      - preset

  metaquast:
    type: object
    properties:
      activate:
        type: boolean
      reference:
        type: string
    required:
      - activate
      - reference

  prodigal:
    type: object
    properties:
      mode:
        type: string
      quiet:
        type: boolean
    required:
      - mode

  prokka:
    type: object
    properties:
      activate:
        type: boolean
      args:
        type: string
      kingdom:
        type: string
    required:
      - activate
      - args
      - kingdom

  diamond:
    type: object
    properties:
      db:
        type: string
      output_type:
        type: integer
      output_format:
        type: string
    required:
      - db

  cog_parser:
    type: object
    properties:
      db:
        type: string
      activate:
        type: boolean
    required:
      - db
      - activate

  vamb:
    type: object
    properties:
      activate:
        type: boolean
    required:
      - activate

  metabat2:
    type: object
    properties:
      activate:
        type: boolean
      seed:
        type: integer
      preffix:
        type: string
    required:
      - activate
      - seed
      - preffix

  concoct:
    type: object
    properties:
      activate:
        type: boolean
    required:
      - activate

  das_tool:
    type: object
    properties:
      activate:
        type: boolean
    required:
      - activate

  postprocessing:
    type: object
    properties:
      activate:
        type: boolean
      runtime_unit:
        type: string
      runtime_cutoff:
        type: integer
      memory_unit:
        type: string
      memory_cutoff:
        type: integer
      memory_gb:
        type: boolean
    required:
      - activate
      - runtime_unit
      - runtime_cutoff
      - memory_unit
      - memory_cutoff
      - memory_gb

required:
  - units
  - trimming
  - merge_reads
  - concatenate_contigs
  - megahit
  - metaquast
  - prodigal
  - prokka
  - diamond
  - cog_parser
  - vamb
  - metabat2
  - concoct
  - das_tool
  - postprocessing
