$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  
  units:
    type: string

  trimming:
    type: object
    properties:
      activate:
        type: boolean
    required:
      - activate

  merge_reads:
    type: object
    properties:
      activate:
        type: boolean
    required:
      - activate

  concatenate_contigs:
    type: object
    properties:
      sequence_length_cutoff: 
        type: integer
    required:
      - sequence_length_cutoff

  prodigal:
    type: object
    properties:
      mode:
        type: string
    required:
      - mode

  hmmsearch:
    type: object
    properties:
      db:
        type: string
    required:
      - db

  diamond:
    type: object
    properties:
      db:
        type: string
    required:
      - db

required:
  - samples
  - prodigal
  - diamond
