$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  
  units:
    type: string

  trimming:
    type: object
    properties:
      activate:
        type: boolean
      phred:
        type: integer
      minimum_length:
        type: integer
      quality_cutoff:
        type: integer
      clip_r5:
        type: integer
      clip_r3:
        type: integer
    required:
      - activate
      - phred
      - minimum_length
      - quality_cutoff
      - clip_r5
      - clip_r3

  merge_reads:
    type: object
    properties:
      activate:
        type: boolean
    required:
      - activate

  concatenate_contigs:
    type: object
    properties:
      sequence_length_cutoff: 
        type: integer
    required:
      - sequence_length_cutoff

  megahit:
    type: object
    properties:
      preset:
        type: string
    required:
      - preset

  prodigal:
    type: object
    properties:
      mode:
        type: string
    required:
      - mode

  hmmsearch:
    type: object
    properties:
      db:
        type: string
    required:
      - db

  diamond:
    type: object
    properties:
      db:
        type: string
      output_type:
        type: integer
    required:
      - db

  hmmer_parser:
    type: object
    properties:
      db:
        type: string
      consistent_pathways:
        type: boolean
    required:
      - db
      - consistent_pathways

  xml_parser:
    type: object
    properties:
      db:
        type: string
    required:
      - db

  vamb:
    type: object
    properties:
      activate:
        type: boolean
    required:
      - activate

required:
  - units
  - trimming
  - merge_reads
  - concatenate_contigs
  - prodigal
  - diamond
  - hmmsearch
  - hmmer_parser
  - xml_parser
