name: Tests

on:
  push:
    branches:
      - main
      - stage
      - cli

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Formatting
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_SNAKEMAKE_SNAKEFMT: true
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Linting
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        snakefile: metaphor/workflow/Snakefile
        args: "--lint"

  run-workflow:
    runs-on: ubuntu-latest
    needs:
      - linting
      - formatting
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      run: |
        pip install .
        metaphor test --confirm -p 2 -m 6144
    # Report testing is deactivated for now
    # - name: Test report
    #   uses: snakemake/snakemake-github-action@v1.24.0
    #   with:
    #     directory: .test
    #     snakefile: workflow/Snakefile
    #     args: "--report report.zip"
