name: Tests

on:
  push:
    branches:
      - main
      - stage

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Formatting
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_SNAKEMAKE_SNAKEFMT: true
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies and lint
      run: |
        pip install snakefmt
        pip install .
        python -m snakefmt metaphor/workflow/Snakefile

  run-workflow:
    runs-on: ubuntu-latest
    needs:
      - linting
      - formatting
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    # Deactivate this for now
    # - name: Install dependencies
    #   run: |
    #     $CONDA/bin/conda env update --file environment.yaml --name base
    - name: Test workflow
      run: |
        conda install -n base -c conda-forge mamba -y
        conda config --set channel_priority strict
        pip install .
        python -m metaphor.cli.cli test --dry-run
